name:         unclechu-i3-status
license:      GPL-3
license-file: LICENSE
homepage:     https://github.com/unclechu/unclechu-i3-status
author:       Viacheslav Lotsmanov
maintainer:   <lotsmanov89@gmail.com>
copyright:    2017 Viacheslav Lotsmanov
category:     System

dependencies:
  - X11
  # - ansi-wl-pprint
  - base
  - base-unicode-symbols
  - data-default
  - dbus
  - directory
  - process
  - unix

ghc-options:
  - -Wall
  - -O2

library:
  source-dirs: src
  build-tools: [hsc2hs]

executables:
  unclechu-i3-status:
    source-dirs:  src
    main:         Main.hs
    dependencies: [unclechu-i3-status]
