name:         unclechu-i3-status
synopsis:     My own status line generator for i3 window manager
license:      GPL-3
license-file: LICENSE
author:       Viacheslav Lotsmanov
maintainer:   Viacheslav Lotsmanov <lotsmanov89@gmail.com>
copyright:    Copyright © 2017–2022 Viacheslav Lotsmanov
category:     System, Desktop Environment
github:       unclechu/unclechu-i3-status

dependencies:
  - aeson >=2.0.0.0
  - async
  - attoparsec
  - base
  - base-unicode-symbols
  - bytestring
  - containers
  - data-default
  - dbus
  - process
  - qm-interpolated-string
  - time
  - unix
  - X11
  - x11-extras

ghc-options: [-Wall]

library:
  source-dirs: src

executables:
  unclechu-i3-status:
    source-dirs:  src
    main:         Main.hs
    dependencies: [unclechu-i3-status]
    ghc-options:  [-threaded]
