resolver: lts-19.9 # ghc-9.0.2
system-ghc: false

packages:
  - '.'

extra-deps:
  - hsc2hs-0.68.4

nix:
  enable: true
  packages:
    - xorg.libX11
    - xorg.libXrandr
    - xorg.libXScrnSaver
    - xorg.libXtst
    - xorg.libXext
    - libxml2
    - gmp
    - zlib
    - dbus
