resolver: lts-20.23 # ghc-9.2.7
system-ghc: false

packages:
  - .
  - x11-extras

extra-deps:
  - hsc2hs-0.68.9

nix:
  enable: true
  packages:
    - xorg.libX11
    - xorg.libXrandr
    - xorg.libXScrnSaver
    - xorg.libXtst
    - xorg.libXext
    - libxml2
    - gmp
    - zlib
    - dbus
